// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9bj9u0o_VtRbu4tDn3jO45UVsj-kzQQM',
    appId: '1:139640029038:web:a6752ab3b931aa1c4b4b7f',
    messagingSenderId: '139640029038',
    projectId: 'wallpaper-389d3',
    authDomain: 'wallpaper-389d3.firebaseapp.com',
    storageBucket: 'wallpaper-389d3.appspot.com',
    measurementId: 'G-NYC32VXN0T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwNTAEqTJYJiMkKDu_RmDjz3RkeUrNtM0',
    appId: '1:139640029038:android:26b0972213e348b74b4b7f',
    messagingSenderId: '139640029038',
    projectId: 'wallpaper-389d3',
    storageBucket: 'wallpaper-389d3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9wIoTb-Iuio9UFKPvsZzXx0AlqquesRM',
    appId: '1:139640029038:ios:7dcebb77f91868824b4b7f',
    messagingSenderId: '139640029038',
    projectId: 'wallpaper-389d3',
    storageBucket: 'wallpaper-389d3.appspot.com',
    iosBundleId: 'com.example.wallpaperApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9wIoTb-Iuio9UFKPvsZzXx0AlqquesRM',
    appId: '1:139640029038:ios:7dcebb77f91868824b4b7f',
    messagingSenderId: '139640029038',
    projectId: 'wallpaper-389d3',
    storageBucket: 'wallpaper-389d3.appspot.com',
    iosBundleId: 'com.example.wallpaperApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9bj9u0o_VtRbu4tDn3jO45UVsj-kzQQM',
    appId: '1:139640029038:web:228c9e20b685a2234b4b7f',
    messagingSenderId: '139640029038',
    projectId: 'wallpaper-389d3',
    authDomain: 'wallpaper-389d3.firebaseapp.com',
    storageBucket: 'wallpaper-389d3.appspot.com',
    measurementId: 'G-29VSB4ZDJP',
  );
}
